modLoader = "javafml"
loaderVersion = "[0,)"
issueTrackerURL = "https://github.com/Bread-Nicecat/RecipeRenderer/issues"
license = "GNU GPL v3"

[[mods]]
modId = "reciperenderer"
version = "${version}"
displayName = "Recipe Renderer"
authors = "Bread_NiceCat"
credits = "mcmod, Architectury-Loom"
description = '''
'''