org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
#properties
archives_name=RecipeRenderer
maven_group=cn.breadnicecat.reciperenderer
enabled_platforms=fabric,neoforge
#versions
minecraft_version=1.21
parchment_version=parchment-1.21:2024.07.28@zip
neoforge_version=21.0.143
fabric_loader_version=0.16.2
fabric_api_version=0.102.0+1.21
jei_version=19.8.2.99
mod_version=3.1.0