modLoader = "javafml"
loaderVersion = "[1,)"
issueTrackerURL = "https://github.com/Bread-Nicecat/RecipeRenderer/issues"
license = "GNU GPL 3.0"

[[mods]]
modId = "reciperenderer"
version = "${version}"
displayName = "Recipe Renderer"
authors = "Bread_NiceCat"
credits = "mcmod, Architectury-Loom"
description = '''
'''
[[mixins]]
config = "reciperenderer-common.mixins.json"

